
server:
  port: 10010
spring:
  application:
    name: itcast-zuul
zuul:
  routes:
    service-provider: /user/**  # 路由名称，可以随便写，习惯上是服务名 方式三
    service-consumer: /consumer/**
  prefix: /api
      # path: /service-provider/**
      # url: http://localhost:8081 方式一
      # serviceid: service-provider # 方式二
eureka:
  client:
    service-url:
      defaultZone : http://localhost:10086/eureka/
