 server:
  port: 8083
 spring:
  #数据库
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-provider # 将来会作为微服务的名称
 eureka:
   client:
     register-with-eureka: true #服务提供方启动时，会检测改该参数是否为true，true就注册给eureka
     service-url:
        defaultZone : http://localhost:10086/eureka/
   instance:
     lease-expiration-duration-in-seconds: 10  # 10秒即过期
     lease-renewal-interval-in-seconds: 5      # 5秒一次心跳




