
server:
  port: 80
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-consumer
eureka:
  client:
    register-with-eureka: true #服务提供方启动时，会检测改该参数是否为true，true就注册给eureka
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:10086/eureka
service-provider: #随机
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能



